#!/bin/bash
#
# Title:      PTS Install base
# Author(s):  MrDoobPG
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Cloning Installer 
      git:
        repo: 'https://github.com/MrDoobPG/Install.git'
        dest: /opt/pgstage
        version: 'master'
        force: no

    - name: Create base folder
      file:
        path: /var/plexguide
        state: directory
        recurse: yes
        owner: '1000'
        group: '1000'
        mode: '0755'

    - name: Create log folder
      file:
        path: /var/plexguide/logs
        state: directory
        recurse: yes
        owner: '1000'
        group: '1000'
        mode: '0755'

    - name: Cloning PTS 
      git:
        repo: 'https://github.com/MrDoobPG/PGBlitz.com'
        dest: /opt/plexguide
        version: 'master'
        force: yes

    - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
        shell: /opt/plexguide/roles/files/task.sh >> /var/log/log-install.txt

    - name: Copy PTS file 
      copy:
        src: /opt/plexguide/roles/files/pts
        dest: /bin/pts
        owner: '1000'
        group: '1000'
        mode: '0755'

    - name: Copy PTS-Useradd file
      copy:
        src: /opt/plexguide/roles/files/ptsadd
        dest: /bin/ptsadd
        owner: '1000'
        group: '1000'
        mode: '0755'

    - name: Copy PTS-System-upgrade file
      copy:
        src: /opt/plexguide/roles/files/upgrade
        dest: /bin/upgrade
        owner: '1000'
        group: '1000'
        mode: '0755'

    - name: Copy PTS-System-update file
      copy:
        src: /opt/plexguide/roles/files/update
        dest: /bin/upgrade
        owner: '1000'
        group: '1000'
        mode: '0755'