#!/bin/bash
#
# Title:      PTS Install base
# Author(s):  MrDoobPG
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
      - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
        shell: ./file/task.sh
