#!/bin/bash
#
# Title:      PTS Install base
# Author(s):  MrDoobPG
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Python3 | Ansible | pip | set values.
      shell: bash /opt/pgstage/roles/files/task.sh >> /var/log/log-install.txt
