#!/bin/bash
#
# Title:      PTS Install base
# Author(s):  MrDoobPG
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
## base install
    - name: Cloning Installer 
      git:
        repo: 'https://github.com/MrDoobPG/Install.git'
        dest: /opt/pgstage
        version: 'master'
        force: yes
